image:
  repository: a2amesh
  tag: '11.0.0'
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

observability:
  otlpEndpoint: http://otel-collector:4318
  metricsPath: /metrics
